### ISSUE TITLE
.desktop should be a valid D-Bus well-known name

### ISSUE THREAD

**Issue by doppelhelix** [xapp-project/gnome-online-accounts-gtk#8]
Since the .desktop file is not named `org.x.GnomeOnlineAccountsGtk.desktop`, some taskbars like `waybar` or the  Gnome dash don't show the correct icon for the running program.

_Reference_: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#file-naming

I can make a pull request but Im not sure about which way to go.
Just edit the [meson.build](https://github.com/linuxmint/gnome-online-accounts-gtk/blob/master/data/meson.build)?
or should [gnome-online-accounts-gtk.desktop.in.in](https://github.com/linuxmint/gnome-online-accounts-gtk/blob/master/data/gnome-online-accounts-gtk.desktop.in.in) be renamed to `org.x.GnomeOnlineAccountsGtk.desktop.in.in` too?

**Comment by clefebvre** [comment]
should it be org.gnome.OnlineAccountsGtk.desktop? We don't have a DNS so it's hard to come up with a reverse DNS..

GNOME dash shouldn't really matter since GNOME has its own UI for GOA in its control center. In fact we should probably hide GOA-GTK in GNOME so it doesn't duplicate the functionality there.

Why isn't waybar supporting the initial version of the spec? Many apps use simple filenames for their desktop file.
